### ISSUE TITLE
Add possibility of a batch file

### ISSUE THREAD

**Issue by FormelLMS** [terrymacdonald/CCDInfo#2]
Probably it's because I am no dev, so I would kindly ask: Is it possible to make a batch file where it is easy to switch between two configurations? This is because for now I can't use the display magician fully, because I use surround in 2560 x 1440 and for two games (The Bus and Fernbus) it isn't possible to drive in 1440p, only in 1080p. Display magician is not changing from 1440 to 1080 for now, CCDInfo is doing the trick for me, but it's a bit a hassle to fiddle with the cmd, so I want to "Do you want to switch to 1. 1440p Surround or 2. 1080p normal and if I press one of the two(or better a switch) the configuration loads. Nothing more than that. Do you think, this should be possible?

**Comment by terrymacdonald** [comment]
@FormelLMS Not something I would normally create as I can't really help each person who uses my software set up their individual machines...I wouldn't have any time to actually do the development work I need to do.

That said, I realise that this may be useful for others too, so I've created a powershell script that you can use as the basis to do what you want. You will need to do some editing yourself to get it set up for your machine.

The powershell file is here: https://raw.githubusercontent.com/terrymacdonald/CCDInfo/main/RunCCDInfo.ps1

To use it, you will need to open it in notepad and edit the menu items to be what you want. There are instructions at the top of the file which should tell you exactly what you need to do. If you have any problems please reply here and I will try to help.

I hope that anyone else who wants to know how to do this will be able to view the file and make it work on their system with the instructions in the powershell file, so I want to make sure the instructions are clear and understandable.
